version: '3.8'
services:
  database:
    container_name: copyfi_postgreSQL
    image: postgres:15
    restart: always
    env_file:
      - .env  
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5430:5430
  server:
    container_name: copyfi_nodeserver
    image: node:18
    working_dir: /usr/src/app
    restart: always
    volumes:
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
      - ./dist:/usr/src/app/dist/
    env_file:
      - .env  
    ports:
      - 3000:3000      
    command: bash -c "npm install && npm run dev"
    links: 
      - database
    depends_on:
      - database      

 


